[package]
name = "oms-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.3.3"
torrent-name-parser = "0.11.0"
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.83"